name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install gcc cmake libsdl2-dev
      - name: Configure CMake
        run: cmake -S . -B build
        working-directory: example/test_app
      - name: Build
        run: make -j 4
        working-directory: example/test_app/build

  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install cmake sdl2
      - name: Configure CMake
        run: cmake -S . -B build
        working-directory: example/test_app
      - name: Build
        run: make -j 4
        working-directory: example/test_app/build

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Fetch SDL2
        shell: powershell
        run: |
          Invoke-RestMethod `
            -Uri https://github.com/libsdl-org/SDL/releases/download/release-2.24.2/SDL2-devel-2.24.2-VC.zip `
            -OutFile D:\SDL2.zip
      - name: Unzip SDL
        run: 7z x D:\SDL2.zip -oD:\
      - name: Configure CMake
        run: |
          dir D:\
          dir D:\SDL2-2.24.2\include
          cmake -DSDL2_LIBRARY="D:\SDL2-2.24.2\lib\x64\SDL2.lib" `
            -DSDL2_INCLUDE_DIR="D:\SDL2-2.24.2\include" `
            -S . -B build
        working-directory: example/test_app
      - name: Build
        run: cmake --build . --parallel 4
        working-directory: example/test_app/build
