name: Release

on:
  push:
    tags:
      - "*.*.*"
    branches:
      - release-workflow

permissions:
  contents: write

jobs:
  linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install \
          libasound2-dev libpulse-dev \
          libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
          libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
          libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
          libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libthai-dev \
          libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev libusb-dev
      - name: Configure CMake
        run: cmake -S . -B build -G Ninja  -DGROWL_CMD_ONLY=1 -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: ninja
        working-directory: build
      - name: Upload growl-cmd artifact
        uses: actions/upload-artifact@v6
        with:
          name: "growlcmd_linux"
          path: "build/growl-cmd"
          overwrite: true

  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Configure CMake
        run: |
          cmake -S . -B build -G Ninja \
            -DGROWL_CMD_ONLY=1 -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
            -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: ninja
        working-directory: build
      - name: Upload growl-cmd artifact
        uses: actions/upload-artifact@v6
        with:
          name: "growlcmd_macos"
          path: "build/growl-cmd"
          overwrite: true

  windows:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Configure CMake
        run: cmake -S . -B build -DGROWL_CMD_ONLY=1
      - name: Build
        run: cmake --build . --parallel 4 --config Release
        working-directory: build
      - name: Upload growl-cmd artifact
        uses: actions/upload-artifact@v6
        with:
          name: "growlcmd_windows.exe"
          path: "build/Release/growl-cmd.exe"
          overwrite: true

  release:
    runs-on: ubuntu-24.04
    name: Create release
    needs: [linux, macOS, windows]
    steps:
      - name: Download growl-cmd Linux
        uses: actions/download-artifact@v8
        with:
          name: growlcmd_linux
          path: linux
      - name: Download growl-cmd macOS
        uses: actions/download-artifact@v8
        with:
          name: growlcmd_macos
          path: macos
      - name: Download growl-cmd Windows
        uses: actions/download-artifact@v8
        with:
          name: growlcmd_windows.exe
          path: windows
      - run: |
          mv linux/growl-cmd growl-cmd-linux64
          mv macos/growl-cmd growl-cmd-macos
          mv windows/growl-cmd.exe growl-cmd-windows.exe
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: growl-cmd-*
